import type { ReportSummary } from "@/lib/meesho-parser";

export type ExportRow = {
  orderId: string;
  sku: string;
  productName: string;
  quantity: number;
  saleAmount: number;
  commission: number;
  shipping: number;
  returnAmount: number;
  rtoAmount: number;
  gst: number;
  netProfit: number;
  isReturn: boolean;
  isRto: boolean;
  state?: string;
};

export function buildCsvExport(
  reportName: string,
  summary: ReportSummary,
  rows: ExportRow[]
): string {
  const header = [
    "Order ID",
    "SKU",
    "Product",
    "Qty",
    "Sale",
    "Commission",
    "Shipping",
    "Return",
    "RTO",
    "GST",
    "Net Profit",
    "Return?",
    "RTO?",
    "State",
  ].join(",");

  const dataLines = rows.map((r) =>
    [
      r.orderId,
      r.sku,
      `"${r.productName.replace(/"/g, '""')}"`,
      r.quantity,
      r.saleAmount,
      r.commission,
      r.shipping,
      r.returnAmount,
      r.rtoAmount,
      r.gst,
      r.netProfit,
      r.isReturn ? "Yes" : "No",
      r.isRto ? "Yes" : "No",
      r.state ?? "",
    ].join(",")
  );

  const summaryBlock = [
    `# Report: ${reportName}`,
    `# Gross Revenue,${summary.grossRevenue}`,
    `# Net Profit,${summary.netProfit}`,
    `# Return Rate,${summary.returnRate.toFixed(2)}%`,
    `# RTO Rate,${summary.rtoRate.toFixed(2)}%`,
    "",
    header,
    ...dataLines,
  ].join("\n");

  return summaryBlock;
}

export function buildPdfHtml(
  reportName: string,
  summary: ReportSummary,
  rows: ExportRow[]
): string {
  const tableRows = rows
    .slice(0, 200)
    .map(
      (r) =>
        `<tr>
      <td>${r.orderId}</td><td>${r.sku}</td><td>${r.productName}</td>
      <td>${r.saleAmount}</td><td>${r.netProfit}</td>
    </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${reportName} - SellerPilot</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 24px; color: #111; }
    h1 { font-size: 20px; }
    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }
    .stat { border: 1px solid #e4e4e7; border-radius: 8px; padding: 12px; }
    .stat label { font-size: 12px; color: #71717a; }
    .stat p { font-size: 18px; font-weight: 600; margin: 4px 0 0; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 16px; }
    th, td { border: 1px solid #e4e4e7; padding: 8px; text-align: left; }
    th { background: #f4f4f5; }
  </style>
</head>
<body>
  <h1>${reportName}</h1>
  <p>Generated by SellerPilot</p>
  <div class="stats">
    <div class="stat"><label>Revenue</label><p>₹${summary.grossRevenue.toLocaleString("en-IN")}</p></div>
    <div class="stat"><label>Net Profit</label><p>₹${summary.netProfit.toLocaleString("en-IN")}</p></div>
    <div class="stat"><label>Return Rate</label><p>${summary.returnRate.toFixed(1)}%</p></div>
  </div>
  <table>
    <thead><tr><th>Order</th><th>SKU</th><th>Product</th><th>Sale</th><th>Profit</th></tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
  ${rows.length > 200 ? `<p><em>Showing 200 of ${rows.length} rows. Export Excel for full data.</em></p>` : ""}
</body>
</html>`;
}
